# Generated by Django 3.0.3 on 2020-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
